ingrid = User.create(first_name: "Ingrid", last_name: "Wong", email: "ingridwong@gmail.com", password:"ingridwong")
victoria = User.create(first_name: "Victoria", last_name: "Hou", email: "victoriahou@gmail.com", password:"victoriahou")
sally = User.create(first_name: "Sally", last_name: "Choi", email: "sallychoi@gmail.com", password:"sallychoi")
ingrid.trips.create(origin: "Taipei, Taiwan", destination: "DC, USA", departing: "15/03/2018", returning: "25/03/2018", transportation: "Plane" )
victoria.trips.create(origin: "DC, USA", destination: "Paris, France", departing: "15/03/2018", returning: "25/03/2018", transportation: "Plane" )
